### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by EMBEDTRON-GH** [LilianManzano/Contact_Manager#1]
Hello Lilian,

i like you Contact Manager and i would like to use it or parts of them in my own project, but i miss a license in your repository.
It is possible to use parts of your code in own projects ? Would you add a license therm ?

Thanks and Greetings 
Gregor

**Comment by LilianManzano** [comment]
Hello,
you are right I will add a free license to clarify this. I now authorize you to use my code and do with it what you want.

Lilian

**Comment by EMBEDTRON-GH** [comment]
That's great 
Thank you
